/* Auto-generated by genmsg_cpp for file /home/kaca/ros/slam_makin/msg/Num.msg */
#ifndef SLAM_MAKIN_MESSAGE_NUM_H
#define SLAM_MAKIN_MESSAGE_NUM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace slam_makin
{
template <class ContainerAllocator>
struct Num_ {
  typedef Num_<ContainerAllocator> Type;

  Num_()
  : num(0)
  , first_name()
  , last_name()
  , age(0)
  , score(0)
  {
  }

  Num_(const ContainerAllocator& _alloc)
  : num(0)
  , first_name(_alloc)
  , last_name(_alloc)
  , age(0)
  , score(0)
  {
  }

  typedef int64_t _num_type;
  int64_t num;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _first_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  first_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  last_name;

  typedef uint8_t _age_type;
  uint8_t age;

  typedef uint32_t _score_type;
  uint32_t score;


private:
  static const char* __s_getDataType_() { return "slam_makin/Num"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "379cbe21d44c48c3d9a5a30aa0ddaafb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int64 num\n\
string first_name\n\
string last_name\n\
uint8 age\n\
uint32 score\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, num);
    ros::serialization::serialize(stream, first_name);
    ros::serialization::serialize(stream, last_name);
    ros::serialization::serialize(stream, age);
    ros::serialization::serialize(stream, score);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, num);
    ros::serialization::deserialize(stream, first_name);
    ros::serialization::deserialize(stream, last_name);
    ros::serialization::deserialize(stream, age);
    ros::serialization::deserialize(stream, score);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(num);
    size += ros::serialization::serializationLength(first_name);
    size += ros::serialization::serializationLength(last_name);
    size += ros::serialization::serializationLength(age);
    size += ros::serialization::serializationLength(score);
    return size;
  }

  typedef boost::shared_ptr< ::slam_makin::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_makin::Num_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Num
typedef  ::slam_makin::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::slam_makin::Num> NumPtr;
typedef boost::shared_ptr< ::slam_makin::Num const> NumConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::slam_makin::Num_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::slam_makin::Num_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace slam_makin

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::slam_makin::Num_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::slam_makin::Num_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::slam_makin::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "379cbe21d44c48c3d9a5a30aa0ddaafb";
  }

  static const char* value(const  ::slam_makin::Num_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x379cbe21d44c48c3ULL;
  static const uint64_t static_value2 = 0xd9a5a30aa0ddaafbULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_makin::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "slam_makin/Num";
  }

  static const char* value(const  ::slam_makin::Num_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::slam_makin::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 num\n\
string first_name\n\
string last_name\n\
uint8 age\n\
uint32 score\n\
\n\
";
  }

  static const char* value(const  ::slam_makin::Num_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::slam_makin::Num_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.num);
    stream.next(m.first_name);
    stream.next(m.last_name);
    stream.next(m.age);
    stream.next(m.score);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Num_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_makin::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::slam_makin::Num_<ContainerAllocator> & v) 
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.first_name);
    s << indent << "last_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "score: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.score);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SLAM_MAKIN_MESSAGE_NUM_H

