/* Auto-generated by genmsg_cpp for file /home/kaca/ros/slam_makin/msg/Robot_position_msg.msg */
#ifndef SLAM_MAKIN_MESSAGE_ROBOT_POSITION_MSG_H
#define SLAM_MAKIN_MESSAGE_ROBOT_POSITION_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace slam_makin
{
template <class ContainerAllocator>
struct Robot_position_msg_ {
  typedef Robot_position_msg_<ContainerAllocator> Type;

  Robot_position_msg_()
  : x(0.0)
  , y(0.0)
  , bearing(0.0)
  {
  }

  Robot_position_msg_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , bearing(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _bearing_type;
  double bearing;


private:
  static const char* __s_getDataType_() { return "slam_makin/Robot_position_msg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "00a455c045be84313ce8061e4f21d9fa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 bearing\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, bearing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, bearing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(bearing);
    return size;
  }

  typedef boost::shared_ptr< ::slam_makin::Robot_position_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_makin::Robot_position_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Robot_position_msg
typedef  ::slam_makin::Robot_position_msg_<std::allocator<void> > Robot_position_msg;

typedef boost::shared_ptr< ::slam_makin::Robot_position_msg> Robot_position_msgPtr;
typedef boost::shared_ptr< ::slam_makin::Robot_position_msg const> Robot_position_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::slam_makin::Robot_position_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::slam_makin::Robot_position_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace slam_makin

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::slam_makin::Robot_position_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::slam_makin::Robot_position_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::slam_makin::Robot_position_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "00a455c045be84313ce8061e4f21d9fa";
  }

  static const char* value(const  ::slam_makin::Robot_position_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x00a455c045be8431ULL;
  static const uint64_t static_value2 = 0x3ce8061e4f21d9faULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_makin::Robot_position_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "slam_makin/Robot_position_msg";
  }

  static const char* value(const  ::slam_makin::Robot_position_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::slam_makin::Robot_position_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 bearing\n\
\n\
";
  }

  static const char* value(const  ::slam_makin::Robot_position_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::slam_makin::Robot_position_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::slam_makin::Robot_position_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.bearing);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Robot_position_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_makin::Robot_position_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::slam_makin::Robot_position_msg_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "bearing: ";
    Printer<double>::stream(s, indent + "  ", v.bearing);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SLAM_MAKIN_MESSAGE_ROBOT_POSITION_MSG_H

