(cl:defpackage slam_makin-srv
  (:use )
  (:export
   "SETPOSITION"
   "<SETPOSITION-REQUEST>"
   "SETPOSITION-REQUEST"
   "<SETPOSITION-RESPONSE>"
   "SETPOSITION-RESPONSE"
   "LANDMARK_SRV"
   "<LANDMARK_SRV-REQUEST>"
   "LANDMARK_SRV-REQUEST"
   "<LANDMARK_SRV-RESPONSE>"
   "LANDMARK_SRV-RESPONSE"
   "SETLANDMARK"
   "<SETLANDMARK-REQUEST>"
   "SETLANDMARK-REQUEST"
   "<SETLANDMARK-RESPONSE>"
   "SETLANDMARK-RESPONSE"
  ))

